# ===============================
# DATABASE CONFIGURATION (H2)
# ===============================
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=create

# Không c?n ch? ??nh H2Dialect n?a
# Hibernate t? nh?n di?n ???c
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Cho phép ch?y data.sql SAU KHI t?o b?ng xong
spring.jpa.defer-datasource-initialization=true

# ===============================
# SQL INIT
# ===============================
spring.sql.init.mode=always

# ===============================
# H2 CONSOLE
# ===============================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console